# Trainings

## IRB training

At Penn State, research is governed by an [Institutional Review Board (IRB)](https://www.research.psu.edu/irb).

All faculty, staff, and students who conduct research need to undergo training from the IRB.
There are different training programs for different types of research, e.g., research with human participants or with non-human animals.

In this lab, all students and staff must complete training in the ethics of conducting research with human participants.

### CITI Training {-}

The [Collaborative Institutional Training Initiative (CITI Program)](https://about.citiprogram.org) provides training modules for researchers.

For Access, go to [CITI training](http://citi.psu.edu/).

Expiration: every 3 years.

- Choose the `University Park, Commonwealth, and other non-Hershey personnel` option  
- Click `LOG IN TO CITI`  

Login = PSU Access ID  

Click `View Courses` next to **Pennsylvania State University**  

#### If you have never taken an IRB course before {-}

- Under the **Learner Tools for Pennsylvania State University** click `Add a course`  
- choose `Institutional Review Board (IRB) training for human subjects research` then `Next`  
- choose `NO, I have Not completed the Human Subjects Research (IRB) Course through CITI. I need to complete the Human Subjects Research (IRB) Course` then `Next`  
- choose `Social Science Research` then `Next`  
- choose `Research with Children` then `Next`  

Take the 'Social and Behavioral Human Subjects Research (IRB) Course'.  

Email your training certificate to the [lab email](mailto:psubrainlab@gmail.com) once this is complete.  

If you have completed this training previously, please email your training certificate.  

#### If you are taking a renewal IRB course {-}

## Other PSU-required trainings

### Annual Compliance Training {-}

For Access go to the [Learning Resource Network](http://lrn.psu.edu/)   

Expiration: Every 365 Days  

#### Login with PSU Access Account {-}

- Click the box `Faculty, Staff & Part time`  
- Then `Login with Access Account`   

- In the Search box, type `Annual Compliance Training`
- Choose `2022 Annual Compliance Training`

#### Login with a LRN Account {-}

If you have difficulty logging in go to: http://lrn.psu.edu/

- Select `Volunteer/Non-Paid Student/Other`  
- Click the box `Volunteer/Student/Other Create LRN Account`

- Supervisory Organization: Choose `Affiliate PENN STATE STUDENT`  
- Location: Choose `Penn State University Park`  
- Position Type: `Student`  
- Enter your password  
- Click the `I'm not a robot` box  
- Click the `Log In` box  

Keep this login information. You will need it to complete these trainings every calendar year.

Email your training certificate to the [lab email](mailto:psubrainlab@gmail.com) once this is complete.

